version: "3"
services:
    backend:
        image: snackoff:latest
        container_name: snackoff
        ports:
            - "5000:5000"
        environment:
            - DB_USER=mysql
            - DB_HOST=mysql
            - DB_NAME=restobar
            - DB_PASSWORD=secret
            - DB_DIALECT=mysql
            - DB_PORT=3306
            - NODE_ENV=development
            - PORT=5000
            - JWT_SECRET=abc123
